config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :materials

   root 'products#index'
   
   get "data" => 'materials#data'
   get "a" => 'materials#a'
   

end

app/models/material.rb
class Material < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy, :edit2]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end
  def data
    @materials = Material.all
  end
  def a
    @materials = Material.all
  end
  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end
  
  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:M_Id, :M_Name, :M_Cost, :Supplier, :S_Address, :S_phone, :Transportation_Time, :Condition, :Number, :Result, :Quality)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @materials = Material.all
  end
  
  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:P_ID, :P_Name, :P_Inventory, :Produce_Dated, :Cost, :Price, :Factory)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>System</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :原料編號 %><br>
    <%= f.number_field :M_Id %>
  </div>
  <div class="field">
    <%= f.label :原料名稱%><br>
    <%= f.text_field :M_Name %>
  </div>
  <div class="field">
    <%= f.label :原料成本 %><br>
    <%= f.text_field :M_Cost %>
  </div>
  <div class="field">
    <%= f.label :供應商 %><br>
    <%= f.text_field :Supplier %>
  </div>
  <div class="field">
    <%= f.label :供應商住址 %><br>
    <%= f.text_field :S_Address %>
  </div>
  <div class="field">
    <%= f.label :供應商電話 %><br>
    <%= f.number_field :S_phone %>
  </div>
  <div class="field">
    <%= f.label :運輸時間 %><br>
    <%= f.number_field :Transportation_Time %>
  </div>
  <div class="field">
    <%= f.label :合格 %>(是為1否為0)<br>
    <%= f.number_field :Quality %>
  </div>
  <div class="field">
    <%= f.label :製成品 %><br>
    <%= f.text_field :Result %>
  </div>
   <div class="field">
    <%= f.label :製造數量 %><br>
    <%= f.number_field :Number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/a.html.erb
<table>
  <thead>
    <tr>
      <th>產品編號Id</th>
      <th>原料名稱</th>
      <th>原料成本</th>
      <th>供應商</th>
      <th>運送時間(日)</th>
      <th>訂購數量</th>
      <th>訂購時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <% if material.Result=='小泡芙'%>
        <td><%= material.M_Id %></td>
        <td><%= material.M_Name %></td>
        <td><%= material.M_Cost %></td>
        <td><%= material.Supplier %></td>
        <td><%= material.Transportation_Time %></td>
        <td><%= material.Number %></td>
         <td><%= material.updated_at %></td>
        <td><%= link_to '資料一覽', material %></td>
        <td><%= link_to '編輯購買量', edit_material_path(material) %></td>
        
      <% else %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

建議搭配組合為:
</br>
越南可可公司生產
 <% @materials.each do |material| %>
 <% if material.Supplier=='越南可可公司'%>
 <%= material.M_Cost*40 %>個
 <% else %>
 <% end %>
 <% end %>
天天樂公司生產
  <% @materials.each do |material| %>
 <% if material.Supplier=='天天樂'%>
 <%= material.M_Cost*20 %>個
 <% else %>
 <% end %>
 <% end %>
 </br>
 <%= link_to '生產系統', root_path %>
<%= link_to '合格原料表', materials_path %>
<%= link_to '原料資料庫', data_path %>

app/views/materials/data.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Materials</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>原料名稱</th>
      <th>原料成本</th>
      <th>供應商</th>
      <th>供應商住址</th>
      <th>供應商電話</th>
      <th>運送時間(日)</th>
      <th>製成品</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.M_Id %></td>
        <td><%= material.M_Name %></td>
        <td><%= material.M_Cost %></td>
        <td><%= material.Supplier %></td>
        <td><%= material.S_Address %></td>
        <td><%= material.S_phone %></td>
        <td><%= material.Transportation_Time %></td>
        <td><%= material.Result %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新增原料', new_material_path %>
<%= link_to '生產系統', root_path %>
<%= link_to '合格原料', materials_path %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form' %>


<%= link_to '合格原料表', materials_path %>
<%= link_to '原料資料庫', data_path %>

app/views/materials/index.html.erb
<h2>合格原料</h2>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>原料名稱</th>
      <th>原料成本</th>
      <th>供應商</th>
      <th>運送時間(日)</th>
      <th>訂購數量</th>
      <th>製成品</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <% if material.Quality == 1 %>
        <td><%= material.M_Id %></td>
        <td><%= material.M_Name %></td>
        <td><%= material.M_Cost %></td>
        <td><%= material.Supplier %></td>
        <td><%= material.Transportation_Time %></td>
        <td><%= material.Number %></td>
        <td><%= material.Result %></td>
        <td><%= link_to '原料明細', material %></td>
      <% else %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to '生產小泡芙', a_path %></br>
<%= link_to '生產系統', root_path %>
<%= link_to '原料資料庫', data_path %>

app/views/materials/new.html.erb
<h1>新增原料</h1>

<%= render 'form' %>

<%= link_to '合格原料表', materials_path %>
<%= link_to '原料資料庫', data_path %>

app/views/materials/pofu.html.erb
<table>
  <thead>
    <tr>
      <th>產品編號Id</th>
      <th>原料名稱</th>
      <th>原料成本</th>
      <th>供應商</th>
      <th>運送時間(日)</th>
      <th>訂購數量</th>
      <th>訂購時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <% if material.Result=='小泡芙'%>
        <td><%= material.M_Id %></td>
        <td><%= material.M_Name %></td>
        <td><%= material.M_Cost %></td>
        <td><%= material.Supplier %></td>
        <td><%= material.Transportation_Time %></td>
        <td><%= material.Number %></td>
         <td><%= material.updated_at %></td>
        <td><%= link_to '資料一覽', material %></td>
        <td><%= link_to '編輯購買量', edit_material_path(material) %></td>
        
      <% else %>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

建議搭配組合為:
</br>
越南可可公司生產
 <% @materials.each do |material| %>
 <% if material.Supplier=='越南可可公司'%>
 <%= material.M_Cost*40 %>個
 <% else %>
 <% end %>
 <% end %>
天天樂公司生產
  <% @materials.each do |material| %>
 <% if material.Supplier=='天天樂'%>
 <%= material.M_Cost*20 %>個
 <% else %>
 <% end %>
 <% end %>
 </br>
 <%= link_to '生產系統', root_path %>
<%= link_to '合格原料表', materials_path %>
<%= link_to '原料資料庫', data_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID</strong>
  <%= @material.M_Id %>
</p>

<p>
  <strong>原料名稱</strong>
  <%= @material.M_Name %>
</p>

<p>
  <strong>原料成本</strong>
  <%= @material.M_Cost %>
</p>

<p>
  <strong>供應商</strong>
  <%= @material.Supplier %>
</p>

<p>
  <strong>供應商地址</strong>
  <%= @material.S_Address %>
</p>

<p>
  <strong>供應商電話</strong>
  <%= @material.S_phone %>
</p>

<p>
  <strong>運輸時間</strong>
  <%= @material.Transportation_Time %>
</p>
<p>
  <strong>製成品</strong>
  <%= @material.Result %>
</p>
<%= link_to '編輯', edit_material_path(@material) %> |
<%= link_to '合格原料', materials_path %>
<%= link_to '原料資料庫', data_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :產品編號 %><br>
    <%= f.number_field :P_ID %>
  </div>
  <div class="field">
    <%= f.label :產品名稱 %><br>
    <%= f.text_field :P_Name %>
  </div>
  <div class="field">
    <%= f.label :產品庫存 %><br>
    <%= f.number_field :P_Inventory %>
  </div>
  <div class="field">
    <%= f.label :庫存日期 %><br>
    <%= f.date_select :Produce_Dated %>
  </div>
  <div class="field">
    <%= f.label :成本 %><br>
    <%= f.text_field :Cost %>
  </div>
  <div class="field">
    <%= f.label :售價 %><br>
    <%= f.text_field :Price %>
  </div>
  <div class="field">
    <%= f.label :工廠 %><br>
    <%= f.text_field :Factory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>生產管理系統</h1>
<h2>產品清單</h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>產品名稱</th>
      <th>產品庫存</th>
      <th>製造日期</th>
      <th>成本</th>
      <th>售價</th>
      <th>生產工廠</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.P_ID %></td>
        <td><%= product.P_Name %></td>
        <td><%= product.P_Inventory %></td>
        <td><%= product.Produce_Dated %></td>
        <td><%= product.Cost %></td>
        <td><%= product.Price %></td>
        <td><%= product.Factory %></td>
        <td><%= link_to '產品明細', product %></td>
        <td><%= link_to '編輯', edit_product_path(product) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h2>生產中商品</h2>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>產品名稱</th>
      <th>製造日期</th>
      <th>成本</th>
      <th>售價</th>
      <th>生產工廠</th>
      <th>原料來源</th>
      <th>生產個數</th>
      <th>生產時間</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
    <% if material.Result == "小泡芙" && material.Number!=0 %>
    <% @products.each do |product| %>
      <tr>
        <% if product.P_Name == "小泡芙" %>
        <td><%= product.P_ID %></td>
        <td><%= product.P_Name %></td>
        <td><%= product.Produce_Dated %></td>
        <td><%= product.Cost %></td>
        <td><%= product.Price %></td>
        <td><%= product.Factory %></td>
        <td><%= material.Supplier %></td>
        <td><%= material.Number/2 %>個</td>
        <td><%= material.updated_at %></td>
      <% else %>
      <% end %>
    <% end %>
    <% end %>
     </tr>
    <% end %>
    <% @materials.each do |material| %>
    <% if material.Result == "保久乳" && material.Number!=0 %>
    <% @products.each do |product| %>
      <tr>
        <% if product.P_Name == "保久乳" %>
        <td><%= product.P_ID %></td>
        <td><%= product.P_Name %></td>
        <td><%= product.Produce_Dated %></td>
        <td><%= product.Cost %></td>
        <td><%= product.Price %></td>
        <td><%= product.Factory %></td>
        <td><%= material.Supplier %></td>
        <td><%= material.Number/6 %>個</td>
        <td><%= material.updated_at %></td>
      <% else %>
      <% end %>
    <% end %>
    <% end %>
     </tr>
    <% end %>
  </tbody>
</table>
<a href="/materials">生產頁</a>



<%= link_to '新產品', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>產品編號</strong>
  <%= @product.P_ID %>
</p>

<p>
  <strong>產品名稱</strong>
  <%= @product.P_Name %>
</p>

<p>
  <strong>庫存數量</strong>
  <%= @product.P_Inventory %>
</p>

<p>
  <strong>製造日期</strong>
  <%= @product.Produce_Dated %>
</p>

<p>
  <strong>成本</strong>
  <%= @product.Cost %>
</p>

<p>
  <strong>售價</strong>
  <%= @product.Price %>
</p>

<p>
  <strong>工廠</strong>
  <%= @product.Factory %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>